---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# biteSizedAQ

<!-- badges: start -->
<!-- badges: end -->

## Background

Air pollution can feel like a giant, overwhelming issue, but the goal of this project is to make air quality (AQ) information accessible and understandable for everyone. The name 'biteSizedAQ' serves as a reminder that even the largest problems can be tackled with small, manageable steps. Instead of feeling overwhelmed, we can break down the air pollution challenge into smaller tasks, taking each one step at a time. By consistently taking these bite-sized, smart steps, we can collectively make significant progress in managing air pollution.

All projects under this repository are free and open, provided under the CC BY 4.0 International License. This ensures that anyone can use, share, and build upon the work, making air quality information more open and accessible for all.

This repository will continue to grow with new projects as and when I find time. To kick things off, check out the first project: using satellite-derived air pollution and population data, combined with India’s block (subdistrict) level shapefile, we've created a detailed air pollution dataset at the block level. Explore the details below to learn more.

Upcoming potential projects include producing satellite-derived PM2.5 data at the village level for over 600,000 Indian villages. Star the repo to keep track of updates.

## General structure and how to navigate projects in this repo

- The number prefix at the start of every project folder/Rmd name is the project id under this repo.

- The latest project will show up top.

- E.g. Project 1 has the id 1. It corresponds to a project folder named `1.ind.block.pm2.5.sat.data.processing` which contains the project's README file. In case of a project involving code and data an additional Rmd containing code can be found at the root of the biteSizedAQ repo. 

- The corresponding helper R script(s) for different projects can be found under `R/` subfolder. These scripts will be grouped in broad themes. E.g. all satellited derived data processing functions will be in the sat data helper script and the names are descriptive enough for it to be easily identifiable.


## Project 4: Monitoring Air Quality: The Power of Satellite Based Remote Sensing

- Read the blog [here]()

- Underlying README Rmd file can be found in the project's respective folder and here is a [quick link to access it]()

## Project 3: Air Quality Data Management Systems Landscape: Navigating Challenges and Opportunities 

- Read the blog [here](https://github.com/AarshBatra/biteSizedAQ/tree/main/3.aq.dms)

- Underlying README Rmd file can be found in the project's respective folder and here is a [quick link to access it](https://github.com/AarshBatra/biteSizedAQ/blob/main/3.aq.dms/README.Rmd)


## Project 2: Deciphering Air Pollution Units: Essential Insights for Informed Action

- Read the blog [here](https://github.com/AarshBatra/biteSizedAQ/tree/main/2.air.pol.units.explainer)

- Underlying README Rmd file can be found in the project's respective folder and here is a [quick link to access it](https://github.com/AarshBatra/biteSizedAQ/blob/main/2.air.pol.units.explainer/README.Rmd)

## Project 1: Block level satellite derived population weighted air pollution dataset for India from 1998-2022

- Read more about this project and download proccessed data from [here](https://github.com/AarshBatra/biteSizedAQ/tree/main/1.ind.block.pm2.5.sat.data.processing). This folder is present at the root of the repo.

- Data Processing pipeline Rmd file for this project: Also, present at the root of the biteSizedAQ repo. Here is a [quick link to access the pipeline](https://github.com/AarshBatra/biteSizedAQ/blob/main/1.ind.block.pm2.5.sat.data.processing.Rmd).





